name: tensora_workspace
description: Workspace definition for the Tensora Dart packages.
version: 0.1.0-dev.1
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

workspace:
  - packages/tensora
  - packages/tensora_nn
  - packages/tensora_optim
  - packages/tensora_data
  - packages/tensora_train

dev_dependencies:
  test: ^1.27.0
  yaml: ^3.1.3
  tensora: ^0.1.0-dev.1
  tensora_data: ^0.1.0-dev.1
  tensora_nn: ^0.1.0-dev.1
  tensora_optim: ^0.1.0-dev.1
  tensora_train: ^0.1.0-dev.1
