name: tensora_flutter
description: Flutter integration for Tensora.
version: 0.1.0-dev.1
repository: https://github.com/eukalpia/tensora

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
